### ISSUE TITLE
Uncaught Error: Cannot find module 'posthtml'

### ISSUE THREAD

**Issue by giuscris** [keevan/atom-attribute-sorter#1]
Hi, I've tried to install your package but an exception was thrown during the process. These are the details:

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [atom-attribute-sorter](https://github.com/keevan/atom-attribute-sorter) package 0.1.0

### Stack Trace

Uncaught Error: Cannot find module 'posthtml'

```
At module.js:545

Error: Cannot find module 'posthtml'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/atom-attribute-sorter/lib/atom-attribute-sorter.js:4:43)
    at /packages/atom-attribute-sorter/lib/atom-attribute-sorter.js:142:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:672952)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3093178)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3082537)
    at PackageManager.t.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:892499)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3026610)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3016890)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3016713)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3024843
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3026861
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172021)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173462)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:901679)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:899088
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:893618)
    at o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1032999)
    at t.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1033153)
```

### Commands

```
```

### Non-Core Packages

```
atom-attribute-sorter 0.1.0 
busy-signal 2.0.1 
docblockr 0.13.7 
github-atom-light-syntax 0.5.0 
intentions 1.1.5 
language-apache 1.8.0 
language-gettext 0.6.1 
language-ini 1.20.0 
language-nginx 0.8.0 
linter 2.3.0 
linter-eslint 8.5.4 
linter-php 1.6.0 
linter-stylelint 4.4.3 
linter-ui-default 1.7.1 
sort-lines 0.19.0 
```

**Comment by keevan** [comment]
Thanks for letting me know. I'll check that out once I get the chance.

**Comment by keevan** [comment]
0.1.1 should fix this issue.

**Comment by giuscris** [comment]
Now it works, thank you!
